### ISSUE TITLE
Get RetryError[<Future at 0x182e2357a60 state=finished raised ValidationError>] with ollama

### ISSUE THREAD

**Issue by s-github-2** [sentient-engineering/sentient#15] opened 2024-09-17 18:34 UTC
### Got an error using ollama (sorry about the formatting not sure how  to reduce font below)
Error executing the command play shape of you on youtube: RetryError[<Future at 0x182e2357a60 state=finished raised ValidationError>]
The full outpuut is
Starting orchestrator
Browser started and ready
Executing command play shape of you on youtube
==================================================
Current State: agentq_base
Agent: sentient
Current Thought:
Plan: none
Completed Tasks: none
==================================================
Error executing the command play shape of you on youtube: RetryError[<Future at 0x182e2357a60 state=finished raised ValidationError>]

**Comment by nischalj10** [comment] 2024-09-17 19:09
hey @s-github-2 - this primarily stems from the fact that the model was not able to generate a valid output. can you tell me which model have you used with ollama?

**Comment by nischalj10** [comment] 2024-09-17 19:17
duplicate of #13

**Closed by nischalj10** 2024-09-17 19:17 UTC
